main():
    continue

# args: --typecheck --no-prelude --no-backtrace
# expected exit status: 101
# expected stderr: tests/ContinueFail.fir:2:5: `break` or `continue` statement not inside a loop
